from Layout.Static.Header_Button_Clear import header_btn_clear


def search_clear(self):
    header_btn_clear(self)
    self.start_box.close()
    self.end_box.close()
    self.change_btn_location.close()
    self.Next_Icon1.close()
    self.Next_Icon2.close()
    self.start_label_start.close()
    self.end_label_start.close()
    self.start_label_date.close()
    self.start_input_location.close()
    self.end_input_location.close()
    self.start_btn_location.close()
    self.end_btn_location.close()
    self.group_box1.close()
    self.radio1.close()
    self.radio2.close()
    self.radio3.close()
    self.radio4.close()
    self.radio5.close()
    self.radio6.close()
    self.Next_Icon_black.close()
    self.start_label_start.close()
    self.date_year.close()
    self.label_year.close()
    self.date_month.close()
    self.label_month.close()
    self.date_day.close()
    self.label_day.close()
    self.search_btn_submit.close()